title: "Unretro"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

collections:
  cars:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    cars:
      name: Karz